package com.app.pojos;

public enum ExpenseCategoryType {
	FOOD,BILLS,UTILITIES,BONUS,ENTERTAINMENT,EDUCATION,PERSONALCARE,HEALTH,FITNESS,KIDS,GIFTS
	,DONATION,INVESTMENTS,TRANSPORT,TAXES,PETCARE,TRAVEL,SAVINGS,CLOTHING,MISCELLANEOUS
	,GROCERIES,AIRTICKETS,BEAUTY,BIKE,BOOKS,CABLE,CAR,CIGARETTE,DRINKS,ELECTRICITY
	,ELECTRONICS,VEGETABLES,FRUITS,GAS,MAINTAINANCE,MOBILE,PETROL,RENT,SALLON,SHOPPING
	,STATIONERY,VACTIONS,HOMELOAN,PERSONALLOAN,EDUCATIONALLOAN,FESTIVAL,CARLOAN,EMI,TOLL 
}

